import type { User, TeamMember, Task, Project, Notification, ActivityItem, Column } from "./types"

export const currentUser: User = {
  id: "user-1",
  name: "Sarah Chen",
  email: "sarah@taskflow.io",
  avatar: "SC",
  role: "admin",
}

export const columns: Column[] = [
  { id: "backlog", title: "Backlog", color: "bg-muted-foreground/20" },
  { id: "todo", title: "To Do", color: "bg-chart-1/20" },
  { id: "in-progress", title: "In Progress", color: "bg-warning/20" },
  { id: "review", title: "Review", color: "bg-chart-4/20" },
  { id: "done", title: "Done", color: "bg-success/20" },
]

export const teamMembers: TeamMember[] = [
  {
    id: "1",
    name: "Sarah Chen",
    email: "sarah@taskflow.io",
    avatar: "SC",
    role: "Product Manager",
    status: "online",
    joinedAt: "2024-01-15",
    userRole: "admin",
  },
  {
    id: "2",
    name: "Alex Rivera",
    email: "alex@taskflow.io",
    avatar: "AR",
    role: "Frontend Developer",
    status: "online",
    joinedAt: "2024-02-20",
    userRole: "member",
  },
  {
    id: "3",
    name: "Jordan Kim",
    email: "jordan@taskflow.io",
    avatar: "JK",
    role: "Designer",
    status: "away",
    joinedAt: "2024-03-10",
    userRole: "member",
  },
  {
    id: "4",
    name: "Taylor Morgan",
    email: "taylor@taskflow.io",
    avatar: "TM",
    role: "Backend Developer",
    status: "online",
    joinedAt: "2024-01-28",
    userRole: "member",
  },
  {
    id: "5",
    name: "Morgan Lee",
    email: "morgan@taskflow.io",
    avatar: "ML",
    role: "QA Engineer",
    status: "offline",
    joinedAt: "2024-04-05",
    userRole: "member",
  },
  {
    id: "6",
    name: "Casey Zhang",
    email: "casey@taskflow.io",
    avatar: "CZ",
    role: "DevOps Engineer",
    status: "online",
    joinedAt: "2024-05-12",
    userRole: "member",
  },
]

export const projects: Project[] = [
  {
    id: "proj-1",
    name: "Website Redesign",
    description: "Complete overhaul of the company website with new branding",
    color: "bg-chart-1",
    progress: 75,
    status: "active",
    members: ["1", "2", "3"],
    tasksCount: 24,
    completedTasks: 18,
    createdAt: "2024-01-10",
    dueDate: "2026-06-30",
  },
  {
    id: "proj-2",
    name: "Mobile App v2.0",
    description: "Major update with new features and performance improvements",
    color: "bg-chart-2",
    progress: 45,
    status: "active",
    members: ["2", "4", "5"],
    tasksCount: 32,
    completedTasks: 14,
    createdAt: "2024-02-15",
    dueDate: "2026-08-15",
  },
  {
    id: "proj-3",
    name: "API Integration",
    description: "Third-party API integrations for enhanced functionality",
    color: "bg-chart-4",
    progress: 90,
    status: "active",
    members: ["4", "6"],
    tasksCount: 16,
    completedTasks: 14,
    createdAt: "2024-03-01",
    dueDate: "2026-05-28",
  },
  {
    id: "proj-4",
    name: "Analytics Dashboard",
    description: "Real-time analytics and reporting dashboard",
    color: "bg-chart-5",
    progress: 30,
    status: "active",
    members: ["1", "2", "3", "4"],
    tasksCount: 20,
    completedTasks: 6,
    createdAt: "2024-04-10",
    dueDate: "2026-09-01",
  },
  {
    id: "proj-5",
    name: "Security Audit",
    description: "Comprehensive security review and improvements",
    color: "bg-success",
    progress: 100,
    status: "completed",
    members: ["4", "5", "6"],
    tasksCount: 12,
    completedTasks: 12,
    createdAt: "2024-01-20",
    dueDate: "2026-04-30",
  },
  {
    id: "proj-6",
    name: "Documentation Update",
    description: "Update all technical documentation and guides",
    color: "bg-warning",
    progress: 15,
    status: "on-hold",
    members: ["1", "5"],
    tasksCount: 8,
    completedTasks: 1,
    createdAt: "2024-05-01",
  },
]

export const tasks: Task[] = [
  {
    id: "task-1",
    title: "Design new dashboard layout",
    description: "Create wireframes and mockups for the new analytics dashboard",
    status: "done",
    priority: "high",
    assignees: ["3"],
    dueDate: "2026-05-20",
    tags: ["design", "ui"],
    comments: 12,
    attachments: 4,
    projectId: "proj-1",
    createdAt: "2024-05-01",
    updatedAt: "2024-05-20",
  },
  {
    id: "task-2",
    title: "Implement authentication flow",
    description: "Add OAuth2 login with Google and GitHub providers",
    status: "review",
    priority: "high",
    assignees: ["2", "4"],
    dueDate: "2026-05-25",
    tags: ["backend", "security"],
    comments: 8,
    attachments: 2,
    projectId: "proj-2",
    createdAt: "2024-05-05",
    updatedAt: "2024-05-22",
  },
  {
    id: "task-3",
    title: "API rate limiting",
    description: "Implement rate limiting for public API endpoints",
    status: "in-progress",
    priority: "medium",
    assignees: ["4"],
    dueDate: "2026-05-28",
    tags: ["backend", "performance"],
    comments: 5,
    attachments: 1,
    projectId: "proj-3",
    createdAt: "2024-05-10",
    updatedAt: "2024-05-21",
  },
  {
    id: "task-4",
    title: "User onboarding flow",
    description: "Design and implement new user onboarding experience",
    status: "in-progress",
    priority: "high",
    assignees: ["1", "3"],
    dueDate: "2026-05-30",
    tags: ["design", "frontend"],
    comments: 15,
    attachments: 6,
    projectId: "proj-1",
    createdAt: "2024-05-08",
    updatedAt: "2024-05-22",
  },
  {
    id: "task-5",
    title: "Database optimization",
    description: "Optimize slow database queries for better performance",
    status: "todo",
    priority: "medium",
    assignees: ["4"],
    dueDate: "2026-06-01",
    tags: ["backend", "database"],
    comments: 3,
    attachments: 0,
    projectId: "proj-3",
    createdAt: "2024-05-12",
    updatedAt: "2024-05-12",
  },
  {
    id: "task-6",
    title: "Mobile responsive fixes",
    description: "Fix layout issues on mobile devices",
    status: "todo",
    priority: "low",
    assignees: ["2"],
    dueDate: "2026-06-05",
    tags: ["frontend", "mobile"],
    comments: 2,
    attachments: 3,
    projectId: "proj-2",
    createdAt: "2024-05-14",
    updatedAt: "2024-05-14",
  },
  {
    id: "task-7",
    title: "Write API documentation",
    description: "Document all public API endpoints",
    status: "backlog",
    priority: "low",
    assignees: ["1"],
    tags: ["documentation"],
    comments: 0,
    attachments: 0,
    projectId: "proj-3",
    createdAt: "2024-05-15",
    updatedAt: "2024-05-15",
  },
  {
    id: "task-8",
    title: "Set up CI/CD pipeline",
    description: "Configure automated testing and deployment",
    status: "backlog",
    priority: "medium",
    assignees: ["4", "6"],
    tags: ["devops"],
    comments: 1,
    attachments: 0,
    projectId: "proj-4",
    createdAt: "2024-05-16",
    updatedAt: "2024-05-16",
  },
  {
    id: "task-9",
    title: "Accessibility audit",
    description: "Perform full accessibility review and fixes",
    status: "backlog",
    priority: "medium",
    assignees: ["3", "5"],
    tags: ["accessibility", "qa"],
    comments: 0,
    attachments: 0,
    projectId: "proj-1",
    createdAt: "2024-05-17",
    updatedAt: "2024-05-17",
  },
  {
    id: "task-10",
    title: "Unit test coverage",
    description: "Increase unit test coverage to 80%",
    status: "review",
    priority: "medium",
    assignees: ["5"],
    dueDate: "2026-05-26",
    tags: ["testing", "qa"],
    comments: 4,
    attachments: 0,
    projectId: "proj-4",
    createdAt: "2024-05-18",
    updatedAt: "2024-05-23",
  },
  {
    id: "task-11",
    title: "Payment integration",
    description: "Integrate Stripe for subscription payments",
    status: "todo",
    priority: "high",
    assignees: ["4"],
    dueDate: "2026-05-18",
    tags: ["backend", "payments"],
    comments: 7,
    attachments: 2,
    projectId: "proj-2",
    createdAt: "2024-05-02",
    updatedAt: "2024-05-19",
  },
  {
    id: "task-12",
    title: "Performance monitoring setup",
    description: "Set up application performance monitoring tools",
    status: "in-progress",
    priority: "medium",
    assignees: ["6"],
    dueDate: "2026-05-29",
    tags: ["devops", "monitoring"],
    comments: 3,
    attachments: 1,
    projectId: "proj-4",
    createdAt: "2024-05-11",
    updatedAt: "2024-05-22",
  },
]

export const notifications: Notification[] = [
  {
    id: "notif-1",
    title: "New task assigned",
    description: "You have been assigned to 'API rate limiting'",
    time: "5 min ago",
    read: false,
    type: "task",
  },
  {
    id: "notif-2",
    title: "Task completed",
    description: "Alex completed 'Design new dashboard layout'",
    time: "1 hour ago",
    read: false,
    type: "task",
  },
  {
    id: "notif-3",
    title: "New team member",
    description: "Casey Zhang joined the team",
    time: "2 hours ago",
    read: true,
    type: "team",
  },
  {
    id: "notif-4",
    title: "Project deadline approaching",
    description: "API Integration is due in 6 days",
    time: "3 hours ago",
    read: true,
    type: "project",
  },
  {
    id: "notif-5",
    title: "Comment on your task",
    description: "Jordan commented on 'User onboarding flow'",
    time: "5 hours ago",
    read: true,
    type: "task",
  },
]

export const activityFeed: ActivityItem[] = [
  {
    id: "act-1",
    user: "Alex Rivera",
    action: "completed task",
    target: "Design new dashboard layout",
    time: "1 hour ago",
    type: "task",
  },
  {
    id: "act-2",
    user: "Jordan Kim",
    action: "commented on",
    target: "User onboarding flow",
    time: "2 hours ago",
    type: "comment",
  },
  {
    id: "act-3",
    user: "Taylor Morgan",
    action: "moved task to review",
    target: "Implement authentication flow",
    time: "3 hours ago",
    type: "task",
  },
  {
    id: "act-4",
    user: "Sarah Chen",
    action: "created project",
    target: "Analytics Dashboard",
    time: "5 hours ago",
    type: "project",
  },
  {
    id: "act-5",
    user: "Casey Zhang",
    action: "joined project",
    target: "API Integration",
    time: "6 hours ago",
    type: "member",
  },
  {
    id: "act-6",
    user: "Morgan Lee",
    action: "started task",
    target: "Unit test coverage",
    time: "8 hours ago",
    type: "task",
  },
]

export const dashboardStats = {
  totalTasks: 48,
  completedTasks: 32,
  pendingTasks: 12,
  overdueTasks: 4,
  activeProjects: 5,
  teamMembers: 6,
}

export const weeklyProgress = [
  { day: "Mon", completed: 4, created: 6 },
  { day: "Tue", completed: 6, created: 3 },
  { day: "Wed", completed: 3, created: 5 },
  { day: "Thu", completed: 7, created: 4 },
  { day: "Fri", completed: 5, created: 2 },
  { day: "Sat", completed: 2, created: 1 },
  { day: "Sun", completed: 1, created: 0 },
]

export const tasksByPriority = [
  { priority: "High", count: 4, fill: "var(--color-chart-5)" },
  { priority: "Medium", count: 8, fill: "var(--color-warning)" },
  { priority: "Low", count: 6, fill: "var(--color-chart-2)" },
]

export const tasksByStatus = [
  { status: "Backlog", count: 3, fill: "var(--color-muted-foreground)" },
  { status: "To Do", count: 4, fill: "var(--color-chart-1)" },
  { status: "In Progress", count: 3, fill: "var(--color-warning)" },
  { status: "Review", count: 2, fill: "var(--color-chart-4)" },
  { status: "Done", count: 8, fill: "var(--color-success)" },
]

export const projectProgress = projects.slice(0, 4).map((p) => ({
  name: p.name,
  progress: p.progress,
  color: p.color,
}))
